In [13]:
import numpy as np
import torch

In [14]:
current_patch = np.array([[[1,2,3], [4,5,6]],
                          [[1,2,3], [4,5,6]],
                          [[10,20,30], [40,50,60]],
                          [[0,2,3], [3,5,6]],
                          ])# shape: B, Min, Max
scale_factor = np.array([2,2,3])
current_patch

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]],

       [[ 0,  2,  3],
        [ 3,  5,  6]]])

In [15]:
current_patch * scale_factor

array([[[  2,   4,   9],
        [  8,  10,  18]],

       [[  2,   4,   9],
        [  8,  10,  18]],

       [[ 20,  40,  90],
        [ 80, 100, 180]],

       [[  0,   4,   9],
        [  6,  10,  18]]])

In [16]:
current_patch[0] = np.array([[1,2,3], [4,5,6]])

In [17]:
temp = torch.tensor(current_patch) 
temp.names = ['B', 'Min', 'Max']
temp.names = [None, None, None]
temp.permute(1,2,0).shape
temp.names

(None, None, None)

In [18]:
import torchio as tio
tio.__version__

'0.18.82'

In [19]:
import os
lengths = []
for object in os.listdir('/local/scratch/clmn1/data/DAVIS/JPEGImages/480p'):
    lengths.append(len(os.listdir(f'/local/scratch/clmn1/data/DAVIS/JPEGImages/480p/{object}')))
print(min(lengths), max(lengths))

25 104


In [20]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr[0:1]

array([1])

In [21]:
import cv2
label = cv2.imread("/local/scratch/clmn1/data/cholecseg8k/video01/video01_00080/frame_80_endo_color_mask.png")
label = cv2.cvtColor(label, cv2.COLOR_BGR2RGB)
label = np.array(label)
mask = label == (0,0,0)
mask = np.all(mask, axis=-1)
mask.shape

(480, 854)

In [22]:
np.unique(np.reshape(label, (-1, 3)), axis=0)

array([[127, 127, 127],
       [186, 183,  75],
       [231,  70, 156],
       [255, 114, 114],
       [255, 160, 165],
       [255, 255, 255]], dtype=uint8)

In [27]:
np.array([1,2,3])

AttributeError: 'numpy.ndarray' object has no attribute '__tuple__'