In [2]:
import numpy as np
import torch

In [2]:
current_patch = np.array([[[1,2,3], [4,5,6]],
                          [[1,2,3], [4,5,6]],
                          [[10,20,30], [40,50,60]],
                          [[0,2,3], [3,5,6]],
                          ])# shape: B, Min, Max
scale_factor = np.array([2,2,3])
current_patch

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]],

       [[ 0,  2,  3],
        [ 3,  5,  6]]])

In [3]:
current_patch * scale_factor

array([[[  2,   4,   9],
        [  8,  10,  18]],

       [[  2,   4,   9],
        [  8,  10,  18]],

       [[ 20,  40,  90],
        [ 80, 100, 180]],

       [[  0,   4,   9],
        [  6,  10,  18]]])

In [4]:
current_patch[0] = np.array([[1,2,3], [4,5,6]])

In [5]:
temp = torch.tensor(current_patch) 
temp.names = ['B', 'Min', 'Max']
temp.names = [None, None, None]
temp.permute(1,2,0).shape
temp.names

/tmp/ipykernel_487932/532464939.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1908.)
  temp.names = ['B', 'Min', 'Max']


(None, None, None)

In [10]:
import torchio as tio
tio.__version__

/home/nlemke/remote/miniconda3/envs/nca/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'0.19.6'

In [2]:
import os
lengths = []
for object in os.listdir('/local/scratch/clmn1/data/DAVIS/JPEGImages/480p'):
    lengths.append(len(os.listdir(f'/local/scratch/clmn1/data/DAVIS/JPEGImages/480p/{object}')))
print(min(lengths), max(lengths))

25 104


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr[0:1]

array([1])

In [11]:
import cv2
label = cv2.imread("/local/scratch/clmn1/data/cholecseg8k/video01/video01_00080/frame_80_endo_color_mask.png")
label = cv2.cvtColor(label, cv2.COLOR_BGR2RGB)
label = np.array(label)
mask = label == (0,0,0)
mask = np.all(mask, axis=-1)
mask.shape

(480, 854)

In [22]:
np.unique(np.reshape(label, (-1, 3)), axis=0)

array([[127, 127, 127],
       [186, 183,  75],
       [231,  70, 156],
       [255, 114, 114],
       [255, 160, 165],
       [255, 255, 255]], dtype=uint8)